version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: quantasight-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-quantasight_search}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-userpassword}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$MYSQL_USER -p$MYSQL_PASSWORD || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quantasight-backend
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_USER: ${MYSQL_USER:-user}
      DB_PASSWORD: ${MYSQL_PASSWORD:-userpassword}
      DB_NAME: ${MYSQL_DATABASE:-quantasight_search}
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret}
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quantasight-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: http://localhost:3001
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
